import shailender from "../shailender.jpeg";
const members = [
  {
    name: "Ayush Kumar",
    img: "https://www.bytecodelearners.club/bytecode-server/storage/app/public/members-image/ayushkumarbgp98@gmail.com.jpg",
    fb: "https://www.facebook.com",
    twitter: "https://www.twitter.com",
    github: "https://www.github.com",
    insta: "https://www.instagram.com",
  },
  {
    name: "Sai kumar",
    img: "https://www.bytecodelearners.club/bytecode-server/storage/app/public/members-image/saikumarnaidusaikumarnaidu@gmail.com.jpg",
    fb: "https://www.facebook.com",
    twitter: "https://www.twitter.com",
    github: "https://www.github.com",
    insta: "https://www.instagram.com",
  },
  {
    name: "Susmita sagar",
    img: "https://www.bytecodelearners.club/bytecode-server/storage/app/public/members-image/susmitasagar038@gmail.com.jpg",
    fb: "https://www.facebook.com",
    twitter: "https://www.twitter.com",
    github: "https://www.github.com",
    insta: "https://www.instagram.com",
  },
  {
    name: "Archana kumnari",
    img: "https://www.bytecodelearners.club/bytecode-server/storage/app/public/members-image/archu0943@gmail.com.jpg",
    fb: "https://www.facebook.com",
    twitter: "https://www.twitter.com",
    github: "https://www.github.com",
    insta: "https://www.instagram.com",
  },
  {
    name: "Umesh kumari",
    img: "https://www.bytecodelearners.club/bytecode-server/storage/app/public/members-image/umeshkumari123029@gmail.com.jpg",
    fb: "https://www.facebook.com",
    twitter: "https://www.twitter.com",
    github: "https://www.github.com",
    insta: "https://www.instagram.com",
  },
  {
    name: "Birender",
    img: "https://www.bytecodelearners.club/bytecode-server/storage/app/public/members-image/bsbawlia@gmail.com.jpg",
    fb: "https://www.facebook.com",
    twitter: "https://www.twitter.com",
    github: "https://www.github.com",
    insta: "https://www.instagram.com",
  },
  {
    name: "Prasann Kumar",
    img: "https://www.bytecodelearners.club/bytecode-server/storage/app/public/members-image/kumarprasann66@gmail.com.jpg",
    fb: "https://www.facebook.com",
    twitter: "https://www.twitter.com",
    github: "https://www.github.com",
    insta: "https://www.instagram.com",
  },
  {
    name: "Shailender",
    img: shailender,
    fb: "https://www.facebook.com",
    twitter: "https://www.twitter.com",
    github: "https://www.github.com",
    insta: "https://www.instagram.com",
  },
  {
    name: "Hari kiran",
    img: "https://www.bytecodelearners.club/bytecode-server/storage/app/public/members-image/harikiran.kante@gmail.com.jpg",
    fb: "https://www.facebook.com",
    twitter: "https://www.twitter.com",
    github: "https://www.github.com",
    insta: "https://www.instagram.com",
  },
  {
    name: "Ashish Sinha",
    img: "https://www.bytecodelearners.club/bytecode-server/storage/app/public/members-image/ashishsinha741@gmail.com.jpg",
    fb: "https://www.facebook.com",
    twitter: "https://www.twitter.com",
    github: "https://www.github.com",
    insta: "htpps://www.instagram.com",
  },
];

export default members;
